title: "Reunion Racing"
baseURL: "https://reunionracing.org"
languageCode: "en-US"
theme: "github.com/kdevo/osprey-delight/v5"
tags: ["cycling"]
disableKinds: ["taxonomy"]
enableEmoji: true
pygmentsUseClasses: true

module:
  imports:
  - path: github.com/kdevo/osprey-delight/v5

Params:
  author:
    name: "Paco Gomez"

  description: "Reunion Racing"

  logoBig: "rr_logo_full_r2.png"

  logoSmall: "rr_crest_r2.png"
  
  background: "tdf-1.jpg"
  
  opengraphImage: "rr_crest_r2.png"

  favicon: "favicon-16x16.png"

  theme: "dedark"

  mdTagline: " "

  enforceSinglePage: false

  copyright: true

  Social:
    - type: facebook  
      url: "https://facebook.com/reunionracing"
    - type: instagram
      url: "https://instagram.com/reunionracing"

  Feat:
    ajaxBasin: "https://usebasin.com/f/05b9ff03d2b1"

    useStructuredData: true

    useTermynal: true

    googleTagManager: ""

    notifyOnNewThemeVersion: true
  
  Image:
    Logo:

    Gallery:
      resize: "600x"

    Background:
      resize: "1920x"
      resizeLQIP: "256x"
  
Menu:
  Main:
    - name: "About"
      identifier: about 
      url: "/#about"
      weight: 1

    - name: "Partners"
      identifier: gallery
      url: "/#partners"
      weight: 3

    - name: "Blog"
      identifier: blog
      url: "/#blog"
      weight: 4

    - name: "Join Us"
      identifier: contact
      url: "/#joinus"
      weight: 5
