title: "Reunion Racing"
baseURL: "https://reunionracing.org"
languageCode: "en-US"
theme: "github.com/kdevo/osprey-delight/v5"
tags: ["cycling"]
disableKinds: ["taxonomy"]
enableEmoji: true
pygmentsUseClasses: true

module:
  imports:
  - path: github.com/kdevo/osprey-delight/v5

Params:
  author:
    name: "Paco Gomez"

  description: "Reunion Racing"

  logoBig: "rr_logo_full_r2.png"

  logoSmall: ""
  
  background: "tdf-1.jpg"
  
  opengraphImage: "/images/osprey-delight.png"

  favicon: "favicon-16x16.png"

  theme: "dedark"

  mdTagline: " "

  enforceSinglePage: false

  copyright: true

  Social:
    - type: facebook  
      url: "https://facebook.com/reunionracing"
    - type: instagram
      url: "https://instagram.com/reunionracing"

  Feat:
    ajaxBasin: "https://usebasin.com/f/{YOUR-12-CHAR-FORM-KEY-HERE}"

    useStructuredData: true

    useTermynal: true

    googleTagManager: ""

    notifyOnNewThemeVersion: true
  
  Image:
    Logo:

    Gallery:
      resize: "600x"

    Background:
      resize: "1920x"
      resizeLQIP: "256x"

Menu:
  Main:
    - name: "About Us"
      identifier: about 
      url: "/#about"
      weight: 1
