title: "Reunion Racing"
baseURL: ${HUGO_BASEURL}
languageCode: "en-US"
theme: "github.com/pacogomez/osprey-delight"
tags: ["cycling"]
disableKinds: ["taxonomy"]
enableEmoji: true
pygmentsUseClasses: true

markup:
  goldmark:
    renderer:
      unsafe: true

module:
  imports:
    - path: github.com/pacogomez/osprey-delight

Params:
  author:
    name: "Paco Gomez"

  description: "Reunion Racing"

  logoBig: "rr_logo_full_r2.png"

  logoSmall: "rr_crest_r2.png"

  background: "tdf-1.jpg"

  opengraphImage: "rr_crest_r2.png"

  favicon: "favicon-16x16.png"

  theme: "dedark"

  mdTagline: " "

  enforceSinglePage: false

  copyright: true

  Social:
    - type: facebook
      url: "https://facebook.com/reunionracing"
    - type: instagram
      url: "https://instagram.com/reunionracing"

  Feat:
    ajaxBasin: "https://usebasin.com/f/05b9ff03d2b1"

    useStructuredData: true

    useTermynal: true

    googleTagManager: ""

    notifyOnNewThemeVersion: true

  Image:
    Logo:

    Gallery:
      resize: "600x"

    Background:
      resize: "1920x"
      resizeLQIP: "256x"

    lazyimg:
      resizer: auto
      renderer: lqip-webp

      lqipSize: "120x Gaussian"
      maxSize: "1920x"
      responsiveSizes:
        ["320x", "640x", "768x", "1024x", "1366x", "1600x", "1920x"]
      resizeOptions: "Lanczos q95"

      noscript: true

Menu:
  Main:
    - name: "About"
      identifier: about
      url: "/#about"
      weight: 10

    #- name: "Partners"
    #identifier: gallery
    #url: "/#partners"
    #weight: 20

    #- name: "Blog"
    #identifier: blog
    #url: "/#blog"
    #weight: 30

    #- name: "Join Us"
    #identifier: contact
    #url: "/#joinus"
    #weight: 40
